spring:
  profiles:
    active: "@activeProfile"
  liquibase:
    change-log: db/db.changelog-master.xml
    enabled: true
    liquibase-schema: public

  spring:
    ai:
      ollama:
        base-url: http://localhost:11434
        chat:
          options:
            model: llama3